spring:
  application:
    name: spring-cloud-eureka
  
server:
  port: 8002

eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka3:8003/eureka/