spring:
  application:
    name: spring-cloud-eureka
  
server:
  port: 8003

eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/