spring:
  application:
    name: spring-cloud-eureka
  #profiles: eureka1
  
server:
  port: 8001

eureka:
  instance:
    hostname: eureka1
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka/